export function pickIcon(title: string, explicitIcon?: string): string {
  if (explicitIcon) return explicitIcon;
  const t = title.toLowerCase();
  if (t.includes("python")) return "🐍";
  if (t.includes("c++") || t.includes("cpp")) return "⚙️";
  if (t.includes("java")) return "☕";
  if (t.includes("linux")) return "🐧";
  if (t.includes("git") || t.includes("github")) return "🔀";
  if (t.includes("html") || t.includes("css")) return "🎨";
  if (t.includes("javascript") || t.includes("js")) return "📜";
  if (t.includes("typescript") || t.includes("ts")) return "📘";
  if (t.includes("react") || t.includes("vue")) return "⚛️";
  if (t.includes("api") || t.includes("http")) return "🔗";
  if (t.includes("数据库") || t.includes("database") || t.includes("sql")) return "🗄️";
  if (t.includes("docker")) return "🐳";
  if (t.includes("网络") || t.includes("network")) return "🌐";
  if (t.includes("安全") || t.includes("security") || t.includes("ctf")) return "🛡️";
  if (t.includes("算法") || t.includes("algo") || t.includes("竞赛")) return "🏆";
  if (t.includes("数据结构") || t.includes("ds")) return "🔢";
  if (t.includes("搜索") || t.includes("search")) return "🔍";
  if (t.includes("动态规划") || t.includes("dp")) return "🧩";
  if (t.includes("图论") || t.includes("graph")) return "🕸️";
  if (t.includes("数学") || t.includes("math")) return "📐";
  if (t.includes("机器学习") || t.includes("ml")) return "🤖";
  if (t.includes("深度学习") || t.includes("dl") || t.includes("pytorch")) return "🧠";
  if (t.includes("numpy") || t.includes("pandas")) return "📊";
  if (t.includes("部署") || t.includes("deploy")) return "🚀";
  if (t.includes("命令行") || t.includes("cli") || t.includes("terminal")) return "💻";
  if (t.includes("markdown")) return "📝";
  if (t.includes("vscode") || t.includes("编辑器")) return "🖊️";
  if (t.includes("身份认证") || t.includes("auth")) return "🔐";
  if (t.includes("框架") || t.includes("framework") || t.includes("spring")) return "🏗️";
  if (t.includes("stl")) return "📦";
  if (t.includes("渗透") || t.includes("pentest")) return "🎯";
  if (t.includes("cv") || t.includes("nlp") || t.includes("大模型")) return "👁️";
  if (t.includes("web")) return "🕸️";
  if (t.includes("训练") || t.includes("training")) return "⚡";
  if (t.includes("专业认知") || t.includes("intro")) return "🎓";
  if (t.includes("编程语言")) return "⌨️";
  return "📋";
}
